package main.java.app.Controller;

import main.java.app.Model.Database;

public class AddMoviesToDatabase {
    public AddMoviesToDatabase(){
        Database.delete();
        Database.movies.add(Database.movies.size(),"Rick And Mortey","RickandMortey.jpg","Comedy","Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.");
        Database.movies.add(Database.movies.size(),"Harry Potter", "HarryPoter.jpg","Fantasy","Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.");
        Database.movies.add(Database.movies.size(),"The Last Of Us", "TheLastOfUs.jpg","Drama","Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.");
        Database.movies.add(Database.movies.size(),"Avatar", "Avatar.jpg","Adventure","In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.");
        Database.movies.add(Database.movies.size(),"Spider Man", "SpiderMan.jpg","Adventure","While being trained by S.H.I.E.L.D., Spider-Man battles evil with a new team of teen colleagues.");
        Database.movies.add(Database.movies.size(),"Home Alone", "HomeAlone.jpg","Family","Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before Christmas Day.");
        Database.movies.add(Database.movies.size(),"The Lord Of The Rings", "TheLordOfTheRings.jpg","Fantasy","Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.");
        Database.movies.add(Database.movies.size(),"One Piece", "OP.jpg","Drama","Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous \"One Piece\" behind. Whoever claims the \"One Piece\" will be named the new King of the Pirates.");
        Database.movies.add(Database.movies.size(),"Rush Hour", "RushHour.jpg","Comedy","When Hong Kong Inspector Lee is summoned to Los Angeles to investigate a kidnapping, the FBI doesn't want any outside help and assigns cocky LAPD Detective James Carter to distract Lee from the case. Not content to watch the action from the sidelines, Lee and Carter form an unlikely partnership and investigate the case themselves.");
        Database.movies.add(Database.movies.size(),"Titanic", "Titanic.jpg","Drama","101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.");
        Database.movies.add(Database.movies.size(),"Mission Impossible", "MissionImpossible.jpg","Adventure","Mission: Impossible is an American television series that chronicles the missions of a team of secret American government agents known as the Impossible Missions Force. The show is a revival of the 1966 TV series of the same name. The only actor to return for the series as a regular cast member was Peter Graves who played Jim Phelps, although two other cast members from the original series returned as guest stars. The only other regular cast member to return for every episode was the voice of \"The Tape\", Bob Johnson.");
        Database.movies.add(Database.movies.size(),"Flash", "Flash.jpg","Action","When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?");
        Database.movies.add(Database.movies.size(),"John Wick", "JohnWick.jpg","Action","With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.");
        Database.movies.add(Database.movies.size(),"Black Adam", "BlackAdam.jpg","Adventure","Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.");
        Database.movies.add(Database.movies.size(),"Interstellar", "Interstellar.jpg","Drama","The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.");
        Database.movies.add(Database.movies.size(),"House", "House.jpg","Family","Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.");
        Database.movies.add(Database.movies.size(),"The Simpsons", "TheSimpsons.jpg","Comedy","Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.");
        Database.movies.add(Database.movies.size(),"Friends", "Friends.jpg","Drama","Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.");
        Database.movies.add(Database.movies.size(),"WWE", "Wwe.jpg","Action","The superstars of World Wrestling Entertainment's \"SmackDown\" brand collide each and every Friday on WWE Friday Night SmackDown.");
        Database.movies.add(Database.movies.size(),"Persona", "Persona.jpg","Adventure","After being diagnosed with Alzheimer's, a retired judicial officer decides to commit a murder that he had been planning for years.");
        Database.save();
        
    }
}
